name = "RxInfer"
uuid = "86711068-29c9-4ff7-b620-ae75d7495b3d"
authors = ["Bagaev Dmitry <d.v.bagaev@tue.nl> and contributors"]
version = "1.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphPPL = "b3f8163a-e979-4e85-b43e-1f63d8c8b42c"
ReactiveMP = "a194aa59-28ba-4574-a09c-4a745416d6e3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"

[compat]
Distributions = "0.25"
GraphPPL = "2.1.0 - 2.1.0"
ReactiveMP = "2.1.0 - 2.1.0, 2"
Reexport = "1.2.0"
Rocket = "1.4.0 - 1.4.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
