name = "RxInfer"
uuid = "86711068-29c9-4ff7-b620-ae75d7495b3d"
authors = ["Bagaev Dmitry <d.v.bagaev@tue.nl> and contributors"]
version = "2.0.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphPPL = "b3f8163a-e979-4e85-b43e-1f63d8c8b42c"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ReactiveMP = "a194aa59-28ba-4574-a09c-4a745416d6e3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
Distributions = "0.25"
Reexport = "1.2.0"
Rocket = "1.4.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
